version: '3.8'

services:
  mc:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      TYPE: PAPER
      EULA: "TRUE"
      MEMORY: "4G"
    volumes:
      - ./data:/data