version: '3.8'

services:
  mc:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      TYPE: PAPER
      VERSION: "1.20.1"
      EULA: "TRUE"
      MEMORY: "4G"
      ENABLE_COMMAND_BLOCK: "true"
      OVERRIDE_SERVER_PROPERTIES: "true"
      GEN_SETTINGS: "void"
      LEVEL: "world_void"
    volumes:
      - ./data:/data